# generated by datamodel-codegen:
#   filename:  storage.json

from __future__ import annotations

from typing import Dict

from pydantic import BaseModel, Extra


class Ledger(BaseModel):
    class Config:
        extra = Extra.forbid

    approvals: Dict[str, str]
    balance: str


class TokenMetadata(BaseModel):
    class Config:
        extra = Extra.forbid

    token_id: str
    token_info: Dict[str, str]


class ObjktwrapFa12Storage(BaseModel):
    class Config:
        extra = Extra.forbid

    ledger: Dict[str, Ledger]
    metadata: Dict[str, str]
    permission_module: str
    token_metadata: Dict[str, TokenMetadata]
    totalSupply: str
