query MyQuery {
  bid(order_by: {price: desc}, where: {tokenAddress: {_eq: "KT1H9Zwm7DporZSKkD1gN9RuZuBsKupKMuMg"}}) {
    id
    bidderId
    level
    price
    startTime
    timestamp
    tokenAddress
    tokenId
    tokenQty
    endTime
    highestBidderId
  }
}
